### ISSUE TITLE
Errors compiling 3.1 branch

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotNativeTools/godot-cpp#284]
I'm having some issues with the 3.1 branch, is there something we need to cherry-pick to this branch that was applies to master?

```
cl /Fosrc\gen\AudioEffectSpectrumAnalyzer.obj /c src\gen\AudioEffectSpectrumAnalyzer.cpp /TP /nologo /EHsc /D_DEBUG /MDd /I. /Igodot_headers /Iinclude /Iinclude\gen /Iinclude\core
AudioEffectSpectrumAnalyzer.cpp
c:\users\basti\development\gdnative\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C3646: 'get_fft_size': unknown override specifier
c:\users\basti\development\gdnative\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C2059: syntax error: '('
c:\users\basti\development\gdnative\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C2238: unexpected token(s) preceding ';'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2039: 'FFT_Size': is not a member of 'godot::AudioEffectSpectrumAnalyzer'
c:\users\basti\development\gdnative\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(16): note: see declaration of 'godot::AudioEffectSpectrumAnalyzer'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2039: 'get_fft_size': is not a member of 'godot::AudioEffectSpectrumAnalyzer'
c:\users\basti\development\gdnative\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(16): note: see declaration of 'godot::AudioEffectSpectrumAnalyzer'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2146: syntax error: missing ';' before identifier 'get_fft_size'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2143: syntax error: missing ';' before '{'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2447: '{': missing function header (old-style formal list?)
scons: *** [src\gen\AudioEffectSpectrumAnalyzer.obj] Error 2
scons: building terminated because of errors.
```

**Comment by BastiaanOlij** [comment]
Looks like this is the same cause as #285 , something in the JSON generation

**Comment by BastiaanOlij** [comment]
This was caused by missing bindings in the audio system. This was fixed upstream in godot 3.1 and followed through in godot_headers 3.1. Should all be good now.

**Comment by 2shady4u** [comment]
Seems that this regression is still present when trying to compile bindings using an api.json generated using the latest stable Godot v3.1.1 branch.
I get the exact same errors when using this self-generated api.json.
Is this an issue that should be addressed in the Godot branch? Or should this be fixed in godot-cpp?
